export const MOCK_GROUPS = [
  {
    id: '1',
    name: '모임12',
    type: '모임',
    category: '친목',
    memberCount: 5,
    profileImage: null,
    isRecruitingSchedule: true,
    recentMembers: ['member1', 'member2', 'member3'],
  },
  {
    id: '2',
    name: '독서 모임',
    type: '모임',
    category: '친목',
    memberCount: 10,
    profileImage: null,
    isRecruitingSchedule: false,
    recentMembers: ['member1', 'member2', 'member3'],
  },
  {
    id: '3',
    name: '영화 감상 모임',
    type: '모임',
    category: '친목',
    memberCount: 15,
    profileImage: null,
    isRecruitingSchedule: false,
    recentMembers: ['member1', 'member2', 'member3'],
  },
  {
    id: '4',
    name: '요리 클래스',
    type: '모임',
    category: '업무',
    memberCount: 8,
    profileImage: null,
    isRecruitingSchedule: true,
    recentMembers: ['member1', 'member2', 'member3'],
  },
  {
    id: '5',
    name: '러닝 크루',
    type: '모임',
    category: '운동',
    memberCount: 25,
    profileImage: null,
    isRecruitingSchedule: true,
    recentMembers: ['member4', 'member5', 'member6'],
  },
  {
    id: '6',
    name: '헬스 동호회',
    type: '모임',
    category: '운동',
    memberCount: 12,
    profileImage: null,
    isRecruitingSchedule: false,
    recentMembers: ['member7', 'member8', 'member9'],
  },
  {
    id: '7',
    name: '우리 동네 청소',
    type: '모임',
    category: '자원봉사',
    memberCount: 18,
    profileImage: null,
    isRecruitingSchedule: true,
    recentMembers: ['member10', 'member11', 'member12'],
  },
  {
    id: '8',
    name: '산책 친구들',
    type: '모임',
    category: '동네생활',
    memberCount: 7,
    profileImage: null,
    isRecruitingSchedule: false,
    recentMembers: ['member13', 'member14', 'member15'],
  },
  {
    id: '9',
    name: '프로젝트 팀',
    type: '모임',
    category: '업무',
    memberCount: 20,
    profileImage: null,
    isRecruitingSchedule: true,
    recentMembers: ['member16', 'member17', 'member18'],
  },
  {
    id: '10',
    name: '음악 감상 모임',
    type: '모임',
    category: '친목',
    memberCount: 13,
    profileImage: null,
    isRecruitingSchedule: false,
    recentMembers: ['member19', 'member20', 'member21'],
  },
  {
    id: '11',
    name: '배드민턴 동호회',
    type: '모임',
    category: '운동',
    memberCount: 16,
    profileImage: null,
    isRecruitingSchedule: true,
    recentMembers: ['member22', 'member23', 'member24'],
  },
  {
    id: '12',
    name: '보드게임 클럽',
    type: '모임',
    category: '친목',
    memberCount: 9,
    profileImage: null,
    isRecruitingSchedule: false,
    recentMembers: ['member25', 'member26', 'member27'],
  },
];

export const MOCK_SCHEDULES = [
  {
    id: '1',
    groupId: '1',
    title: '12월 정기 모임',
    date: '12월 15일 ~ 12월 15일',
    dateRange: '1일간',
    location: '강남역 4번 출구',
    organizerName: '김민수',
    memberCount: 5,
    isRecruiting: true,
    hasVote: true,
    votedMemberCount: 2,
    description:
      '이번 달 정기 모임입니다.\n강남역 근처 카페에서 만나 간단한 다과와 함께 이야기 나누는 시간을 가지려고 합니다.\n편한 복장으로 오시면 됩니다.',
  },
  {
    id: '2',
    groupId: '1',
    title: '신제품 출시 이벤트',
    date: '12월 10일 ~ 12월 10일',
    dateRange: '1일간',
    location: '마케팅 팀',
    organizerName: '이지은',
    memberCount: 200,
    isRecruiting: false,
    hasVote: false,
    votedMemberCount: 0,
    description:
      '신제품 출시를 기념하는 특별한 이벤트입니다.\n많은 분들의 참여 부탁드립니다.',
  },
  {
    id: '3',
    groupId: '2',
    title: '이달의 책 토론',
    date: '1월 20일 ~ 1월 20일',
    dateRange: '1일간',
    location: '홍대 북카페',
    organizerName: '박서연',
    memberCount: 10,
    isRecruiting: true,
    hasVote: true,
    votedMemberCount: 7,
    description:
      '이번 달에 읽은 책에 대해 함께 이야기를 나누는 시간입니다.\n준비물: 책, 필기도구',
  },
  {
    id: '4',
    groupId: '3',
    title: '주말 영화 관람',
    date: '1월 18일 ~ 1월 18일',
    dateRange: '1일간',
    location: 'CGV 강남점',
    organizerName: '최영수',
    memberCount: 15,
    isRecruiting: false,
    hasVote: false,
    votedMemberCount: 0,
    description:
      '새로 개봉한 영화를 함께 관람합니다.\n관람 후 간단한 식사 예정입니다.',
  },
  {
    id: '5',
    groupId: '5',
    title: '한강 러닝',
    date: '1월 12일 ~ 1월 12일',
    dateRange: '1일간',
    location: '반포 한강공원',
    organizerName: '정태희',
    memberCount: 25,
    isRecruiting: true,
    hasVote: true,
    votedMemberCount: 18,
    description: '매주 토요일 아침 한강 러닝 모임입니다.\n초보자도 환영합니다!',
  },
  {
    id: '6',
    groupId: '5',
    title: '마라톤 대회 참가',
    date: '2월 5일 ~ 2월 5일',
    dateRange: '1일간',
    location: '서울 올림픽공원',
    organizerName: '정태희',
    memberCount: 15,
    isRecruiting: true,
    hasVote: true,
    votedMemberCount: 10,
    description: '하프 마라톤 대회에 함께 참가합니다.\n완주를 목표로 화이팅!',
  },
  {
    id: '7',
    groupId: '7',
    title: '동네 청소 봉사',
    date: '1월 25일 ~ 1월 25일',
    dateRange: '1일간',
    location: '성수동 일대',
    organizerName: '강민지',
    memberCount: 18,
    isRecruiting: true,
    hasVote: false,
    votedMemberCount: 0,
    description:
      '우리 동네를 깨끗하게 만드는 봉사활동입니다.\n장갑과 쓰레기봉투는 제공됩니다.',
  },
  {
    id: '8',
    groupId: '9',
    title: '분기 회의',
    date: '1월 30일 ~ 1월 31일',
    dateRange: '2일간',
    location: '본사 대회의실',
    organizerName: '윤상호',
    memberCount: 20,
    isRecruiting: false,
    hasVote: true,
    votedMemberCount: 20,
    description:
      '1분기 실적 발표 및 2분기 계획 수립 회의입니다.\n발표 자료 사전 준비 필수',
  },
  {
    id: '9',
    groupId: '11',
    title: '배드민턴 연습',
    date: '1월 16일 ~ 1월 16일',
    dateRange: '1일간',
    location: '송파구 체육센터',
    organizerName: '이준호',
    memberCount: 16,
    isRecruiting: true,
    hasVote: true,
    votedMemberCount: 12,
    description: '주 2회 정기 연습입니다.\n라켓은 개인 지참 부탁드립니다.',
  },
  {
    id: '10',
    groupId: '4',
    title: '이탈리안 요리 클래스',
    date: '1월 22일 ~ 1월 22일',
    dateRange: '1일간',
    location: '요리 스튜디오',
    organizerName: '홍지민',
    memberCount: 8,
    isRecruiting: true,
    hasVote: true,
    votedMemberCount: 6,
    description: '파스타와 피자를 만들어봅니다.\n재료비 별도 1만원',
  },
];

export const MOCK_MEMBERS = [
  {
    id: '1',
    nickname: '닉네임',
    profileImage: null,
    joinDate: '2023-01-15',
  },
  {
    id: '2',
    nickname: '홍길동',
    profileImage: null,
    joinDate: '2023-01-15',
  },
  {
    id: '3',
    nickname: '김철수',
    profileImage: null,
    joinDate: '2023-02-20',
  },
  {
    id: '4',
    nickname: '이영희',
    profileImage: null,
    joinDate: '2023-03-10',
  },
  {
    id: '5',
    nickname: '박민준',
    profileImage: null,
    joinDate: '2023-04-05',
  },
  {
    id: '6',
    nickname: '최서연',
    profileImage: null,
    joinDate: '2023-04-12',
  },
  {
    id: '7',
    nickname: '정도윤',
    profileImage: null,
    joinDate: '2023-05-08',
  },
  {
    id: '8',
    nickname: '강예진',
    profileImage: null,
    joinDate: '2023-05-20',
  },
  {
    id: '9',
    nickname: '윤지호',
    profileImage: null,
    joinDate: '2023-06-15',
  },
  {
    id: '10',
    nickname: '임수아',
    profileImage: null,
    joinDate: '2023-07-01',
  },
  {
    id: '11',
    nickname: '한준우',
    profileImage: null,
    joinDate: '2023-07-18',
  },
  {
    id: '12',
    nickname: '오현지',
    profileImage: null,
    joinDate: '2023-08-05',
  },
  {
    id: '13',
    nickname: '신태영',
    profileImage: null,
    joinDate: '2023-08-22',
  },
  {
    id: '14',
    nickname: '배소희',
    profileImage: null,
    joinDate: '2023-09-10',
  },
  {
    id: '15',
    nickname: '곽민서',
    profileImage: null,
    joinDate: '2023-09-28',
  },
  {
    id: '16',
    nickname: '송현우',
    profileImage: null,
    joinDate: '2023-10-12',
  },
  {
    id: '17',
    nickname: '남지우',
    profileImage: null,
    joinDate: '2023-10-30',
  },
  {
    id: '18',
    nickname: '안서준',
    profileImage: null,
    joinDate: '2023-11-08',
  },
  {
    id: '19',
    nickname: '유다은',
    profileImage: null,
    joinDate: '2023-11-20',
  },
  {
    id: '20',
    nickname: '권하준',
    profileImage: null,
    joinDate: '2023-12-05',
  },
];

export const MOCK_VOTED_MEMBERS = [
  {
    id: '1',
    name: '홍길동',
    profileImage: null,
  },
  {
    id: '2',
    name: '김철수',
    profileImage: null,
  },
  {
    id: '3',
    name: '이영희',
    profileImage: null,
  },
  {
    id: '4',
    name: '박민준',
    profileImage: null,
  },
  {
    id: '5',
    name: '최서연',
    profileImage: null,
  },
  {
    id: '6',
    name: '정도윤',
    profileImage: null,
  },
  {
    id: '7',
    name: '강예진',
    profileImage: null,
  },
  {
    id: '8',
    name: '윤지호',
    profileImage: null,
  },
];

export const CATEGORIES = [
  '전체',
  '친목',
  '업무',
  '운동',
  '동네생활',
  '자원봉사',
];
